### ISSUE TITLE
Review & Extend this Repo

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-typescript#20]
@MikeRund at present this repo is quite superficial and only gives a `basic` overview. 💭 
But it's at a point where _you_ can help! 🔰 

# Todo

+ [ ] Read through the repo as it currently stands;
  + [ ] Install the dependencies
  + [ ] `try` the examples
+ [ ] **_Extend_ it** by filling in gaps as you google for stuff. Ref: #1 and #2

Aim to spend `T4h` e.g. when you're back in Blighty and bored. 💭 
If you can think of a mini-project e.g. calculator to build, that could be an `<option>`.
You _could_ consider using `TypeScript` for your _personal_ site which appears to be built with `React`. 
_Many_ companies have jumped on the `TypeScript + React` bandwagon. 
The `FinTech Co` I was working with over the summer uses it a _lot_. 
There are Pros & Cons to `TypeScript` focus on the Pros. 🙊 

Familiarize yourself with it _enough_ to legitimately put it on your CV even if you don't use it for a mega project. 
If you _like_ it enough to use it for a _personal_ project, go for it! (and report back!)
